apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-generator-config
  namespace: anatheobald
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  DATASET_PATH: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
  DATASET_VERSION: "v1"
