apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anatheobald
  name: frontend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      containers:
        - name: frontend
          image: quay.io/anatheobald/frontend-api:2a7d153
          command: ["python3", "app.py"]  
          ports:
            - containerPort: 50001
          env:
            - name: FLASK_RUN_PORT
              value: "50001"
          volumeMounts:
            - name: spotify-dataset
              mountPath: /data
              readOnly: true
            - name: model-volume
              mountPath: /model
              readOnly: true
      volumes:
        - name: spotify-dataset
          hostPath:
            path: /home/datasets/spotify
            type: Directory
        - name: model-volume
          persistentVolumeClaim:
            claimName: project2-pvc-anatheobald