apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: anatheobald
  name: project2-pvc-anatheobald
spec:
  storageClassName: default-storage-class-anatheobald
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: anatheobald
